### ISSUE TITLE
Wrong order of get_profile and get_wordlist in workflow

### ISSUE THREAD

**Issue by fmatter** [cldf-datasets/lapollaqiang#5]
`text.get_profile(clts=args.clts.api, filename=ds.dir / 'output' / 'automated-orthography.tsv')` should come before `wl = text.get_wordlist(doculect='Qiang', profile=ds.etc_dir / 'orthography.tsv')`, since `orthography.tsv` is based on `automated-orthography`.

**Comment by LinguList** [comment]
Yes and no. To run the workflow from zero, yes, you will have to make the profile first. But in our case, we had the manually annotated profile, and only added this line in order to show how it can be done if one wants an automated profile. I agree it may be confusing, but the illustration of the automated profile works, so I see no direct need to change the code here, rather modifying the explanation in NOTES.md.
